### ISSUE TITLE
Plurals thing problem

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#1]
During combat, the names of the consumable weapons are written in the plural. Moreover, the ending of such a word is taken from somewhere else, from another part of the code. Since we didn't translate it, all we see here is reverse latinization and we see "ДРОТИКЫ" (Ы=S). We need "ОВ" RUS ending in a word in this case. DART = ДРОТИК, 11 DARTS = 11 ДРОТИКОВ. Or, if we have a character limit, we can do this: 11 DARTS = 11 ДРОТИКИ.

![DARTS](https://user-images.githubusercontent.com/77742895/114103999-c32d1d80-98d2-11eb-94dd-0df1aaa68a27.jpg)

**Comment by Reotor** [comment]
![upload_2021-4-4_15-55-1](https://user-images.githubusercontent.com/77742895/114104595-d2609b00-98d3-11eb-9103-6eb7aa41c39b.png)

**Comment by grannypron** [comment]
Attached are my notes on the case so far.
[plurals debugging.txt](https://github.com/grannypron/PoR_L10n/files/6289802/plurals.debugging.txt)

**Comment by grannypron** [comment]
FOUND IT:  18C0 - 18C1 in START.EXE.   There is actually space for two characters, remarkably!

**Comment by grannypron** [comment]
My final notes on the subject for posterity's sake and my own reference later:



So, the s gets copied into 0000:1A66F in memory.  If the EDI is really relative to the base pointer, then the base pointer must be at 1A66F-3D2F = 16940.  No dice - a bunch of 00s


Let's look at the DS and CS registers, the data and code segements.  CS is 0C9A. Go to C 0C9A:0000 in dosbox debugger.  I can find those bytes at 0010:C9A0 in the memdump and at 0000:C9A0.  which is the location in CS but left shifted one.  

If i go to 0000:25C0 I do find what looks like the start of something, an abrupt transition from 00s to non-nulls.  What is the relationship between the data segment and the ESI/EDI registers.   Are they REALLY relative to the EBP?  BOTH of them?  and what is the DS register's relationship to the EBP?

Check this: 
https://stackoverflow.com/questions/4903906/assembly-using-the-data-segment-register-ds

For instance in an instruction like "mov ax, [0x1234]" the CPU would use "DS * 0x10 + 0x1234" as the effective address (the first term resolves to zero in your case.) When you have one like "mov ax, [BP+0x32]" then the CPU will use "SS * 0x10 + BP + 0x32". 

So, check the DS * 0x10 + 0440: 025C0 + 0440 = 02A00.  And there in memory is this
(from 29EF-2A00) - the 2A00 being the damn "s".
Lf    Ytn  * s


So, now do D 0000:2A00 to watch that data and see when THAT gets poked into memory.  Or maybe do a memory watch breakpoint on it idk


66 20 20 20 06 20 59 74 6E


18C0

**Comment by Reotor** [comment]
Many thanks! I did not look in other places in the game, but there, in the battle, where there was an error before, now everything is displayed correctly!

![Plurals](https://user-images.githubusercontent.com/77742895/114285199-ff40b980-9a5d-11eb-8a2f-7144c270766c.jpg)

**Comment by Reotor** [comment]
As I expected, there was a new plural problem for items. The fact is that in our language, when it comes to the number of objects from two to four, we add the ending "а". That is, there will be, for example, not "2 дротик**ов**", but "2 дротик**а**". 

![здгкфд](https://user-images.githubusercontent.com/77742895/115090053-8093c280-9f1c-11eb-9ef8-e896482e4182.jpg)

And that's just for a word "дротик".  For other words, the plural endings will be different. I will show you later with specific examples. For now, at least that needs to be fixed. 

*If you want to fix everything at once now, I need a list of all things in the game that can stack and require the use of plurals for translation.

**Comment by grannypron** [comment]
I don't see that being realistically doable - at least not for me.  The logic of the game really only assumes a single string for plurals.  We can keep this ticket open but that would take some serious new assembly to be written and I doubt that anyone would take that on.  :/

**Comment by grannypron** [comment]
We could possibly remove the plurals altogether and replace them with blank spaces if that is better

**Comment by Reotor** [comment]
> We could possibly remove the plurals altogether and replace them with blank spaces if that is better

Honestly, I would remove the plural altogether. This will not affect normal perception of the gameplay. Let it be, for example: "1 дротик", "2 дротик", etc

**Comment by grannypron** [comment]
Plurals have now been removed (i.e. replaced by blank spaces) in the latest patch
