### ISSUE TITLE
"Exit to DOS" option does not work

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#10]
"Exit to DOS" (Уйти в дос) option does not work in the main menu. 

![Exit to DOS](https://user-images.githubusercontent.com/77742895/115469229-ed6ccc80-a23c-11eb-9193-cf4841a80628.jpg)

I press the "У" key, which is in the same place as the Latin "E" (Exit), but instead of closing the window with the game, nothing happens.

**Comment by grannypron** [comment]
This is because the Drop Character menu item is translated to a string that starts with "У": Удалить

We can change either menu item, as long as the hotkeys don't overlap.

**Comment by Reotor** [comment]
**E**xit to DOS ---> **У**йти в ДОС ---> **В**ыйти в дос (replace "E" to "D").

**Comment by grannypron** [comment]
👍  Patch now has this string changed and hotkey activated.
