### ISSUE TITLE
The "AC" numerical characteristic is displayed incorrectly when creating a character

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#100]
When creating a character, at the stage when you can "reroll the dice" of characteristics by selecting the "NO" (НЕТ) option, an extra zero is added to "AC" (КБ) numeric value.

Screenshot of the Russian version (with an issue):

![AC](https://user-images.githubusercontent.com/77742895/126042254-0f5de216-ca8d-48d5-94d8-1eaa8702cc8e.jpg)

Screenshot of the original (no issue):

![AC2](https://user-images.githubusercontent.com/77742895/126042272-346f9cf2-f9fe-4079-8b62-8f0722e97c18.jpg)

_*After proceeding to further character settings, this numerical characteristic begins to display correctly (without an extra zero)._

**Comment by grannypron** [comment]
Note, this is not related to 1BE1-1BE6 ("AC  HP" substitution) in the start.exe swaps
