### ISSUE TITLE
Need to change translation and hotkey for "DROP" option

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#102]
When we go: "VIEW" ---> "DROP", need to change translation and hotkey for "DROP" (УД.) option.

![drop](https://user-images.githubusercontent.com/77742895/126048069-04c551b3-51d6-428f-aa62-172c1f21a5ab.jpg)

DROP ---> УД. ---> **ВЫБР** ---> **DS<H**

"**У**" (E) hotkey ---> "**В**" (D) hotkey

**Comment by grannypron** [comment]
This will change it in the same places as #15   Still want to do that?

**Comment by Reotor** [comment]
> This will change it in the same places as #15 Still want to do that?

Not yet, we need to find a common word that works for both of these situations. At the moment we have not found such a word. I posted on our forum with a question https://www.old-games.ru/forum/threads/pool-of-radiance.97690/page-32#post-1756479.

**Comment by Reotor** [comment]
"ДОЛОЙ" - This word would be the best 5 characters option. I really hope that you will be able to use this word as a "DROP" translation:

DROP ---> УД. ---> **ДОЛОЙ** ---> **LJKJQ**

**Comment by grannypron** [comment]
Does not look good.  Because this is in the overlay file, I'm having trouble adjusting the lengths.  Can we shrink "Trade" (Обмен) by 1?

![image](https://user-images.githubusercontent.com/19980049/132419831-9b00eb66-7356-4b79-85aa-f8bea0e41f93.png)

**Comment by Reotor** [comment]
> Can we shrink "Trade" (Обмен) by 1?

Yes, we can shorten the name of this menu item. I need to consult with the guys from our forum...

**Comment by Reotor** [comment]
Is the "TRADE" string in this menu also used when trading in a shop? In this case, we will need to choose a word that is suitable when exchanging money and things with other characters, and when trading with a merchant. In our language, different words are much more often used for these situations.

**Comment by grannypron** [comment]
Good question and I don't know.  There are two different "Trade" words in the GAME.OVR so any time you see "Trade" in the menus it is one of those two.  I think PROBABLY one is for the Character View - Items / Spells / Trade / Drop / Exit menu and another is in the Ready / Use / Trade / Drop Inventory menu?   Not sure if these are used in other windows, like the store, though...

**Comment by Reotor** [comment]
> Good question and I don't know.

Well... Let's try to use:

TRADE ---> СБЫТ ---> C<SN

This word is relatively well suited to potentially possible situations in the game: both when trading in a store, and when transferring items to another characters.

**Comment by grannypron** [comment]
Looks much better now.  But the hotkey for the new Drop word is not working (I think).  I will file a second ticket for that.

**Comment by grannypron** [comment]
It looks like the lengthening of the string from DROP to ДОЛОЙ is causing the freeze.  If I use ДОЛО, it does not freeze :(

Imma close #142 and reopen this one to find a solution for a better translation of DROP

**Comment by grannypron** [comment]
The freeze was probably related to #103 and not from the lengthening to ДОЛОЙ because after the 103 fix, it seems to be working just fine.
