### ISSUE TITLE
Need translation corrections for spell book

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#104]
Need few translation corrections for spell book (we open it when encamp to memorize spells).

1. SPELLS IN SPELL BOOK ---> ЗАКЛ. В КНИГУ ---> ЗАКЛИНАНИЯ ---> PFRKBYFYBZ

![spellbook6](https://user-images.githubusercontent.com/77742895/126049437-6847f3c4-59ad-46e5-9f6a-94d038250cc0.jpg)

2. It is necessary to remove the ending ---> **'s**, which is constantly displayed after the character's name. 

![spellbook2](https://user-images.githubusercontent.com/77742895/126049495-0824e299-320d-4df7-9463-d83e4d7b59f6.jpg)

![spellbook3](https://user-images.githubusercontent.com/77742895/126049501-8ae8a745-03c5-4247-9091-2e76093bdcc4.jpg)

_In the Russian language there is a similar rule, but it is more complicated. The good news is that we can allow this ending to be removed entirely here._

3. CAN MEMORIZE ---> МОЖЕТ ЗАПОМН ---> ЗАПОМНИТ ---> PFGJVYBN

![spellbook4](https://user-images.githubusercontent.com/77742895/126049536-aa1eaea9-eced-42d6-97eb-8f3c1b54ec0e.jpg)

_This simplification will avoid shortening the word and will not distort the meaning._

4. CHOOSE SPELL ---> ВЫБР. ЗАКЛ ---> ВЫБРАННОЕ ---> DS<HFYYJT

![spellbook5](https://user-images.githubusercontent.com/77742895/126049586-f026d63d-ad34-46aa-ad1f-7a3d8477c4e6.jpg)

_If we can fix this, then we will remove one more abbreviation of the word, which will have a positive visual impact._

5. When we accept spells to memorize and choose "EXIT", then we get to the menu, which lists the spells that will be memorized. Need to do next replace:
 
ЗАКЛ. БУДЕТ ВЫУЧЕНО ---> ЗАПОМНИТ ---> PFGJVYBN

![spellbook8](https://user-images.githubusercontent.com/77742895/126049895-6c1c0a7f-0193-40b5-bd97-15a09b6852cd.jpg)

6. When the list of spells is long, options СЛ/ПР (NEXT/PREV) appear at the bottom. Need to add dot at the end of theese abbreviations:

![spellbook9](https://user-images.githubusercontent.com/77742895/126050160-66add2b1-7162-4a39-845b-4e7969cf73e6.jpg)

СЛ. or **СЛЕД.** (the second option is possible without a dot at the end, if it does not fit, BEST option if fits)

![spellbook9a](https://user-images.githubusercontent.com/77742895/126050164-e8b32e8b-31df-4a51-9b46-0884ecc8c51c.jpg)

ПР. or **ПРЕД.** (the second option is possible without a dot at the end, if it does not fit, BEST option if fits)

**Comment by grannypron** [comment]
's can be found at 2C94-2C95 in START.EXE (uncompressed)

**Comment by grannypron** [comment]
Alright for 1 above - two phrases are paired up here:  "Spells" and "in spell book".  The same "Spells" string is also paired with "in Memory", "on Scroll", "on Scrolls", "to choose from", "to be memorized", and "to be scribed".

So, I guess one way we could do it is to change "Spells" to just be blank and then adjust its pairings as necessary, but that makes me a little afraid of where else the "Spells" string might be used.  Any way to adopt that kind of phrase pairing scheme in Russian?

**Comment by Reotor** [comment]
> that makes me a little afraid of where else the "Spells" string might be used

Well... I think that nothing terrible will happen if we abandon "Spells" word in some places of the game interface. If something goes wrong, we will correct all the nuances in the process of further game-testing

**Comment by grannypron** [comment]
Did 1-5.  I think we might need to be concerned with these translations now that "Spells" is blank:

418|in Memory|в  памяти
419|in Spell Book|заклинания
420|on Scroll|на свиток
421|on Scrolls|на свитки
422|to choose from|выбирается из
423|to be memorized|запомнит
424|to be scribed|будет записа.

**Comment by grannypron** [comment]
Looks like СЛ and ПР have aleady been expanded under some other change.  I think these are handled under 

549| Next| След
550| Prev| Пред

And are used for every list in the game that requires pagination.

![image](https://user-images.githubusercontent.com/19980049/134831610-b5184dd6-3dbe-4f96-ab9b-c5b7c668ccd5.png)

**Comment by Reotor** [comment]
> And are used for every list in the game that requires pagination.

This will be OK for every list

**Comment by Reotor** [comment]
> I think we might need to be concerned with these translations now that "Spells" is blank:

418|in Memory|запомнено
419|in Spell Book|в книге
420|on Scroll|в свитке
421|on Scrolls|в свитках
422|to choose from|выбрать из
423|to be memorized|чтобы запомнить
424|to be scribed|для записи

*_I am not sure yet of the correctness of such a translation, since I need to understand exactly in what situations these messages appear..._

**Comment by Reotor** [comment]
Should there be an empty space here? 

![EMPTY](https://user-images.githubusercontent.com/77742895/135271974-5479c71b-45c5-4786-acb5-95830082da92.jpg)

What in the original game here?
