### ISSUE TITLE
Words "HITPOINTS" and "AC" on the battlefield are not translated

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#106]
Words "HITPOINTS" and "AC" on the battlefield are not translated:

![combat@](https://user-images.githubusercontent.com/77742895/126138999-1d0f3b87-c889-4803-afdf-2158eda3c172.jpg)

HITPOINTS ---> **ЗДОРОВЬЕ** ---> PLJHJDMT
AC ---> **КБ** ---> R<

**Comment by grannypron** [comment]
Yep these were just somehow not found when they extracted strings from the binary.  Also need a translation for "Helpless" which is in the binary and is used when someone is held by like a Hold Person spell or asleep from a Sleep spell.  I used "Беспомощный", but that was a bit too long.

**Comment by Reotor** [comment]
> Also need a translation for "Helpless"

Sorry, I did not read this message carefully the last time, I skipped this question.

Helpless ---> **НЕМОЩНЫЙ** ---> YTVJOYSQ

**Comment by Reotor** [comment]
Just now, on the forum, it was decided to nevertheless change the translation of the "Helpless" word to: 

**УЯЗВИМЫЙ** ---> EZPDBVSQ
