### ISSUE TITLE
It is necessary to set the correct hotkeys for YES/NO on the battlefield

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#109]
On the battlefield, when the question is asked whether to attack an ally, the hotkeys for YES/NO (ДА/НЕТ) do not work correctly.

![sousnik](https://user-images.githubusercontent.com/77742895/126149132-ffdc518b-adc3-49bd-900f-c3dd679471fd.jpg)

Need to make the appropriate hotkeys. ("Д" for "ДА" and "Н" for "НЕТ").

**Comment by grannypron** [comment]
151DE in GAME.OVR needs to go from 59 (Y) to 4C (L)

**Comment by grannypron** [comment]
With the amount of 3C59 byte sequences still in GAME.OVR (could be interpreted as comparing against "Y"), I doubt this will handle all the combat Yes/No prompts, but it might.  I think others might be if you cast a spell against a friendly?  Not sure.  Should be QC'd.
