### ISSUE TITLE
Incorrect hotkeys for "YES"/"NO"

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#11]
When selecting a character icon, when asked if the icon is ok, hotkeys for "Да"/"Нет" ("Yes"/"No") strings don't work correctly. 

![ok](https://user-images.githubusercontent.com/77742895/115475320-03cc5580-a248-11eb-8fca-f4d3a19bb621.jpg)

The key "Y" still works in the Latin layout for "Yes", the "N" key does not work at all, and the "L" key works for "No" instead.

It is necessary to add the "Д" (L) key for "Да" and the "Н" key for "Нет".

**Comment by Reotor** [comment]
I think, the same problem as  #9

**Comment by Reotor** [comment]
Same problem when deleting a character:

![yesno1](https://user-images.githubusercontent.com/77742895/115480123-8ce88a00-a252-11eb-9692-dc060869c947.jpg)

![yesno2](https://user-images.githubusercontent.com/77742895/115480127-8f4ae400-a252-11eb-9074-243e49970410.jpg)

**Comment by grannypron** [comment]
All these should be fixed now.

**Comment by Reotor** [comment]
**Same problem when asked whether to continue the battle:**

![yn](https://user-images.githubusercontent.com/77742895/115528350-a1e90b80-a29a-11eb-8df5-dbc49d8d8427.jpg)
