### ISSUE TITLE
An extra, unnecessary menu item on the battlefield?

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#110]
Apparently this menu item shouldn't be here:

![NEEE](https://user-images.githubusercontent.com/77742895/126192597-bfefb6b3-f02f-4402-9f83-b1bc630ec86b.jpg)

![HEEE2](https://user-images.githubusercontent.com/77742895/126192743-9f6c8251-4cd9-4712-b210-51f4817f8f6a.jpg)

**Comment by grannypron** [comment]
This is actually a stub I had put in there for the "Turn" command.  As in the cleric's ability to "turn away" the undead.

**Comment by Reotor** [comment]
If the limit for "TURN" is 4 characters then: TURN ---> **И**ЗГН ---> **B**PUY
If there is no limit, then: TURN ---> **И**ЗГНАТЬ ---> **B**PUYFNM

**Comment by grannypron** [comment]
It does look like we are limited to 4 :/

![image](https://user-images.githubusercontent.com/19980049/131593324-352b1e8e-47d2-4918-9c58-c23da6ef1020.png)
