### ISSUE TITLE
The name of the menu on battlefield needs to be corrected

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#112]
When adjusting the battle speed on the battlefield, the current speed value merges with the menu name.

![tempo3](https://user-images.githubusercontent.com/77742895/126196764-76720547-86fe-48fe-93a2-837ffde818f6.jpg)

It is necessary to put spaces in the appropriate place in the text so that it turns out as in the original.

![tempo2](https://user-images.githubusercontent.com/77742895/126196978-5fcec98f-595b-480a-acee-9e200c7c4126.jpg)

If for this it will be necessary to shorten the name of the menu, we can make the following adjustment: СКОР. ИГРЫ ---> **СК. ИГРЫ** ---> CR. BUHS

_However, this is only as a last resort, because it will be difficult to understand what it is about..._

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/133697514-813fac23-fd97-4d02-aec6-b0ea02c9a056.png)
Got it
