### ISSUE TITLE
In the "ALTER" menu, the hotkeys for YES/NO ("DROP") option do not work correctly

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#118]
ENCAMP ---> ALTER ---> DROP --- ДА/НЕТ (YES/NO)

![Drop2](https://user-images.githubusercontent.com/77742895/126856899-9bddf2bd-2fab-49d9-a2a6-cdccce0c95ee.jpg)

When you press the "Д" (L) key, the option "NO" is triggered.
When you press the "Н" (Y) key, the option "YES" is triggered.

Should be the other way around.

**Comment by grannypron** [comment]
From the debugger, I believe this is the cmp,59 at 191B7-191B8

**Comment by grannypron** [comment]
Confirmed.  Changed 59 to 4C to make it respond to L instead of Y at 191B8 in GAME.OVR
