### ISSUE TITLE
The letter "Ж" is displayed incorrectly on the battlefield

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#121]
On the battlefield, the letter "Ж" is displayed incorrectly. Instead of the letter "Ж", a colon is displayed:

![Ж](https://user-images.githubusercontent.com/77742895/126894057-02588695-4aaf-4d82-af0b-460dc4c8e864.jpg)

**Comment by grannypron** [comment]
How'd you even get a character with an Ж in it?  When I try to create a character like that I can't save it to disk!

**Comment by Reotor** [comment]
> How'd you even get a character with an Ж in it?

This is not the name of the character. This is the name of the monster (which we translated with the GBC).

**Comment by grannypron** [comment]
Aha!

**Comment by grannypron** [comment]
I see.  Ж maps to ";", not ":".  These will all have to be changed via MonsterMod.exe.  Fortunately, I only saw 7 of them.
