### ISSUE TITLE
Need to change translation for SPECTRE

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#123]
Need to change "SPECTRE" monster translation to GHBPHFR.

SPECTRE ---> **ПРИЗРАК** ---> GHBPHFR

For this purpose, I have prepared the .hdiff files:

[SPECTRE_CORRECTIONS.zip](https://github.com/grannypron/PoR_L10n/files/6873907/SPECTRE_CORRECTIONS.zip)

If I make any mistake while creating these files, please do the translation yourself. Thank you!

**Comment by grannypron** [comment]
Included the diff files in the patch.zip distro

**Comment by grannypron** [comment]
I had to recreate these.  Can you tell me what you changed when you did these?  I found the SPECTRE in MONCHAR2.DAX (number 14), but what did you change in MONCHAR4.DAX?  I noticed that there was another black spirit looking monster that I think was a wigtht(?) that was translated as ПРИЗРАК (number 9) - did you change that to something else in MONCHAR2?

**Comment by Reotor** [comment]
I honestly don't remember. Maybe I accidentally translated the wrong string? This is how we translated the WIGHT:

WIGHT ---> УМЕРТВИЕ ---> EVTHNDBT

And **ПРИЗРАК** is a **SPECTRE**

**Comment by Reotor** [comment]
I looked at the MONCHAR4.DAX , string №9. This is **WRAITH**

Yes!  I translate **WRAITH** as **ПРИЗРАК** too... So... We need to find another translation for this monster. 
I will consult on the forum.

**Comment by Reotor** [comment]
After some discussion on the forum, we came to the conclusion that it is necessary to make the following adjustments in the names of monsters:

WIGHT ---> УМЕРТВИЕ ---> EVTHNDBT
WRAITH ---> ПРИЗРАК ---> GHBPHFR
SPECTER ---> ДУХ ---> LE{

I hope this will not cause any difficulties...
