### ISSUE TITLE
To continue testing the game, a patch is needed to fix these major issues

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#125]
**In order for us to be able to continue testing the game normally, a patch is needed in which these main problems will be fixed:**

1. Letters "Ё" will be present; ---> https://github.com/grannypron/PoR_L10n/issues/80
2. Letters "Х" will be present;
3. Double quotes will be present; ---> https://github.com/grannypron/PoR_L10n/issues/78
3. The translated names of the monsters will be embedded in the patch (as already been done in this version of the patch 
[patch (+monsters).zip](https://github.com/grannypron/PoR_L10n/files/6883191/patch.%2Bmonsters.zip)). ---> https://github.com/grannypron/PoR_L10n/issues/94

When the above issues are present, it makes it difficult to concentrate on testing the game, I am constantly distracted by these extra "Э" letters or the missing "Ё" letter or "Х" letter...

Huge request to make this patch as soon as possible so that I can continue testing. Thank you very much in advance!

**Comment by grannypron** [comment]
Sorry I think I built from an old directory that didn't have the earlier fixes.  I think the latest should have them now.

**Comment by Reotor** [comment]
Thank you! it looks like now all the main issues have been fixed and we can continue testing.

**Comment by Reotor** [comment]
I asked you to [replace the font](https://github.com/grannypron/PoR_L10n/issues/124) because some of the letters overlapped a little. Hope it didn't take too much of your time.
