### ISSUE TITLE
It is necessary to correct a translation of the "Pool" word

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#126]
Since we made the decision to change the translation of the game's name to "Сияющий источник" it is necessary to correct a "Pool" word to "ИСТОЧНИК" in those files where it appears in the context of the game's name. Well:

POOL OF RADIANCE ---> СИЯЮЩИЙ ПРУД ---> **СИЯЮЩИЙ ИСТОЧНИК** ---> CBZ>OBQ BCNJXYBR

**Comment by grannypron** [comment]
I actually couldn't find this string in ECL3 or START.EXE and there is only one mention of it in GAME.OVR that looks like it is already translated the way you want it so I think we are good:

345|With the power of the pool of radiance|С мощью сияющего источника,

If the old string shows up in there somewhere, lmk and we will track it down.
