### ISSUE TITLE
In the last patch, instead of the letters "Э", the letters "Ё"

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#127]
I found that in the last patch there is again a problem with letters. This time all the letters "Э" are replaced by the letters "Ё".

![Ё-Э](https://user-images.githubusercontent.com/77742895/128029731-970564ee-d58a-4079-b38d-089afa1cc84c.jpg)

**Comment by grannypron** [comment]
I see.  I am getting confused between З, Э, and Ё.  This should just require a font mod to the first character in the font bmp.

**Comment by grannypron** [comment]
This should be fixed in the main game files, but isn't fixed in the ECL3 translation, so it will probably show up there until we do the next batch of fixes for ECL3.

**Comment by grannypron** [comment]
Reopening to remind me to re-import ECL3
