### ISSUE TITLE
It is necessary to change the title picture of the game

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#128]
Due to the fact that we decided to change the name of the game, it is necessary to change the title picture. Here is this picture:

![upload_2021-8-4_9-8-17](https://user-images.githubusercontent.com/77742895/128132970-c3b2b1df-ce85-42b0-a755-15ba902fd5ac.png)

**Comment by grannypron** [comment]
Used https://github.com/grannypron/PoR_L10n/commit/7e04b1deea4a6da162056943a23283cd2fb9405e code to update the title screen
