### ISSUE TITLE
**Need to somehow remove "Б" and "Ю" symbols from this string (when ending the battle):**

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#13]
**Need to somehow remove "Б" and "Ю" symbols from this string (when ending the battle):**

![vvodu](https://user-images.githubusercontent.com/77742895/115529106-4a976b00-a29b-11eb-9a35-611b17b89288.jpg)

_Originally posted by @Reotor in https://github.com/grannypron/PoR_L10n/issues/12#issuecomment-823911885_

**Comment by grannypron** [comment]
Should be in the latest patch.

**Comment by Reotor** [comment]
TY! 

![VVOD_fixed](https://user-images.githubusercontent.com/77742895/116573375-693dd780-a915-11eb-9a4f-7ac194429527.jpg)
