### ISSUE TITLE
It is necessary to implement translation of game passwords

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#130]
It is necessary to implement translation of game passwords. We did not find in which game file the password strings are, so if there are still untranslated passwords, please tell us on the forum where to find them. Or you can just list them and we will make a translation.

**At the moment we have translated the following passwords:**

SHESTNI ---> **ЧЕСТНЫЙ** ---> XTCNYSQ
NOKNOK ---> **ТУКТУК** ---> NERNER
LUX ---> **СВЕТ** ---> CDTN
SAMOSUD ---> **САМОСУД** ---> CFVJCEL

**Related Video:**

https://youtu.be/RrhEWCJtVRw?list=PLD70F07199384757A&t=582

**Comment by grannypron** [comment]
SHESTNI, LUX, and SAMOSUD are in ECL4_021 (Sokal Keep).   NOKNOK is in ECL7_023 (Sorcerer's Isle 2).

**Comment by grannypron** [comment]
Added NOKNOK as 290 in ECL7: https://www.old-games.ru/translate/index.php?translationid=159

Added the other three as 252, 253, 254 in ECL4: https://www.old-games.ru/translate/index.php?translationid=156
