### ISSUE TITLE
We have finished translating strings of the "ECL1" file. You can embed these strings into the game

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#131]
We have finished translating strings of the "ECL1" file. You can embed these strings into the game.

https://www.old-games.ru/translate/index.php?translationid=153

**Comment by grannypron** [comment]
I need to drop about 75 characters between #s 1 and 124 to fit the original ECL size 😬  They can be from any words anywhere in those first 124 entries

**Comment by Reotor** [comment]
Done!

**9 THE BIDDING ESCALATES TO 5,000 GOLD PIECES -- HIGH BID FROM A MAN IN PLAIN CLOTHES, NEXT TO AN OGRE.**
СТАВКА ПОВЫШАЕТСЯ ДО 5000 ЗОЛОТЫХ - И ВЫШЕ ВСЕХ ПОСТАВИЛ ЧЕЛОВЕК В СКРОМНОЙ ОДЕЖДЕ, СТОЯЩИЙ ЗА ОГРОМ.
-7

**14 YOU UP THE BID. MONSTERS NEARBY TURN, STARE,**
ВЫ ПОДНИМАЕТЕ СТАВКУ. БЛИЖАЙШИЕ МОНСТРЫ ПОВОРАЧИВАЮТСЯ, ГЛАЗЕЮТ,
-8

**22 THE MONSTERS LOOK AROUND FOR A SCAPEGOAT. THEIR EYES FALL UPON YOUR PARTY, THEN THEY**
МОНСТРЫ ОСМАТРИВАЮТСЯ В ПОИСКАХ КОЗЛА ОТПУЩЕНИЯ. ИХ ВЗГЛЯД ПАДАЕТ НА ВАШ ОТРЯД, ЗАТЕМ ОНИ
-2

**25 HE GLARES AT YOU,'ONE OF YOU SHALL PAY FOR THIS INSULT. WHO WILL IT BE?'WHAT DO YOU DO?**
ОН ПЯЛИТСЯ НА ВАС: "ОДИН ИЗ ВАС ЗАПЛАТИТ ЗА ЭТО ОСКОРБЛЕНИЕ. КТО ИМ СТАНЕТ?" - ВАШИ ДЕЙСТВИЯ?
-10 

**44 WE ARE RECRUITING CREATURES FOR OUR TEMPLE TO THE NORTHEAST. ARE YOU INTERESTED?'**
"НАБИРАЕМ НАЁМНИКОВ ДЛЯ НАШЕГО ХРАМА НА СЕВЕРО-ЗАПАДЕ. ИНТЕРЕСУЕТ?"
-3 

**47 WE ARE HIRING CREATURES TO RECOVER OUR TEMPLE. ARE YOU INTERESTED?'**
"НАНИМАЕМ СУЩЕСТВ ДЛЯ ВОССТАНОВЛЕНИЯ НАШЕГО ХРАМА. ИНТЕРЕСУЕТ?"
-3 

**52 'DO YOU THINK HE'LL REALLY SHOW UP -- THE BOSS I MEAN?'**
"ДУМАЕШЬ, ОН ПРАВДА ПОЯВИТСЯ - В СМЫСЛЕ, БОСС?"
-3

**54 THE PLAZA AHEAD IS CROWDED WITH MONSTERS. HOW WILL YOU PROCEDE?**
НА ПЛОЩАДИ ВПЕРЕДИ ЕСТЬ МОНСТРЫ. ВАШИ ДЕЙСТВИЯ?
-6

**55 STRIDE BOLDLY FORWARD!**
БЕССТРАШНО ИДТИ ВПЕРЁД!
-2

**57 SNEAK, REMAINING UNSEEN**
ПРОКРАСТЬСЯ
-15

**58 ORCS**
ОРКИ
-1

**59 HOBGOBLINS**
ХОБГОБЛИНЫ
-1

**60 OGRES**
ОГРЫ
-1

**61 RUSH TO ATTACK.**
НАПАДАЮТ.
-10

**84 MONSTERS INSULT YOUR ABILITIES AND PARENTAGE.**
МОНСТРЫ ОСКОРБЛЯЮТ ВАС И ВАШИХ РОДИТЕЛЕЙ.
-7

**Total:** -79 characters

**Comment by grannypron** [comment]
I'm sorry it's still crying for about 30 more characters.  Because the text gets compressed, it's a little hard to tell exactly how long it is :/   If we could cut 50 that should do it for sure.  Or we could try less.

**Comment by Reotor** [comment]
Done!

**89 JOIN IN HEAVY DRINKING**
ПОПОЙКА
-10

**90 YOU HAD A GREAT TIME UNTIL YOU ALL PASSED OUT. YOUR PURSE IS MISSING.**
ВЫ ОТЛИЧНО ПРОВОДИТЕ ВРЕМЯ, ПОКА НЕ ОТРУБАЕТЕСЬ. ВАШ КОШЕЛЬ ИСЧЕЗ.
-5

**91 YOUR ACTIONS ANGER THE PATRONS AND THEY ATTACK.**
ЗАВСЕГДАТАИ ВОЗМУЩЕНЫ ВАШИМИ ДЕЙСТВИЯМИ, ОНИ АТАКУЮТ.
-4

**95 THE BATTLE IS OVER, THE PATRONS RETURN TO DRINKING.**
КОНЕЦ БОЯ. ЗАВСЕГДАТАИ ПРОДОЛЖАЮТ ПИТЬ.
-8

**96 MANY CREATURES HAVE GATHERED. THE ROBED ORC STANDS AND CALLS OUT,'FIRST, TO SHOW YOUR LOYALTIES, KILL THE UNBELIEVERS.' HE POINTS AT YOUR GROUP.**
СОБРАЛОСЬ МНОГО СУЩЕСТВ. ОРК В МАНТИИ СТОИТ И ВЫКЛИКАЕТ: "СНАЧАЛА, ЧТОБЫ ВЫКАЗАТЬ ВАШУ ВЕРНОСТЬ, УБЕЙТЕ НЕВЕРНЫХ". - ОН УКАЗЫВАЕТ НА ВАС.
-6

**103 THE MONSTERS STAND READY**
МОНСТРЫ ГОТОВЫ
-11

**115 THE BUCCANEER SMILES.'THAT IS SUFFICIENT PAYMENT.' HE LEAVES.**
ПИРАТ ЛЫБИТСЯ: "ЭТОГО ХВАТИТ". - ОН УХОДИТ.
-3

**116 'WE'LL LET YOU OFF THIS TIME.' THE MONSTERS SCUTTLE AWAY.**
"НА ЭТОТ РАЗ МЫ ПОЗВОЛИМ ВАМ УЙТИ". - МОНСТРЫ УДИРАЮТ.
-9

**Total:** -56 characters
