### ISSUE TITLE
It is necessary to implement a translated string that is not available from our translation system

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#134]
There is a string in the game that is not available in our translation system. Need to implement translation directly into the game. 

**Here is this string:**

'IT IS TODAY'S PASSWORD AT THE MAIN GATE INTO THE HEDGE MAZE. ALAS, I CAN NOT HELP YOU WITH THAT FOR I HAVE NOT BEEN INSIDE. BUT I HAVE HEARD THE MAZE IS DEADLY!'

**Here is the translation:**

"ЭТО СЕГОДНЯШНИЙ ПАРОЛЬ К ГЛАВНЫМ ВОРОТАМ В ЛАБИРИНТ ЖИВОЙ ИЗГОРОДИ. УВЫ, Я НЕ СМОГУ ПОМОЧЬ ВАМ В ЭТОМ ДЕЛЕ, ВЕДЬ Я НИКОГДА НЕ БЫВАЛ ВНУТРИ. НО СЛЫШАЛ, ЧТО ТАМ СМЕРТЕЛЬНО ОПАСНО!"

**Comment by grannypron** [comment]
This is found at ECL5, ID4 (ECL5_004)

**Comment by Reotor** [comment]
> This is found at ECL5, ID4 (ECL5_004)

I do not find this string in ECL5 in our translation system. 

![ID4a](https://user-images.githubusercontent.com/77742895/129671911-b7ef546a-102f-4b4b-8516-a6a24c31b1da.jpg)

Apparently not all strings were imported.

**Comment by Reotor** [comment]
*This string is also missing under other numbers (I tried to find it using the browser search)...

**Comment by Reotor** [comment]
Our translator has slightly changed the translation of this string. Now it will be shorter, which will never hurt us. 

**Please use this variant when embedding the string in the original ECL:**

"ЭТО СЕГОДНЯШНИЙ ПАРОЛЬ К ГЛАВНЫМ ВРАТАМ ЛАБИРИНТА ЖИВОЙ ИЗГОРОДИ. УВЫ, ТУТ Я НЕ СМОГУ ВАМ ПОМОЧЬ, ВЕДЬ Я НЕ БЫВАЛ ВНУТРИ. НО ПО СЛУХАМ, ЭТО СМЕРТОНОСНЫЙ ЛАБИРИНТ!"

**Comment by grannypron** [comment]
I added this to the СП for ECL5 along with the translation as 435 so it will be there when we are ready.

https://www.old-games.ru/translate/index.php?translationid=157&page=2
