### ISSUE TITLE
A couple of missed translations in ECL3_000

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#140]
8: PRESS <RETURN> OR BUTTON TO CONTINUE
86: SKULLCRUSHER SPEAKS, 'I MUST GO TO MY MASTER NOW.' 

The second one has a space after it.

**Comment by Reotor** [comment]
**8: PRESS OR BUTTON TO CONTINUE** ---> 
НАЖМИТЕ ВВОД, ЧТОБЫ ПРОДОЛЖИТЬ

**86: SKULLCRUSHER SPEAKS, 'I MUST GO TO MY MASTER NOW.'** ---> 
ЧЕРЕПОЛОМ ГОВОРИТ: 'ТЕПЕРЬ Я ДОЛЖЕН ОТПРАВИТЬСЯ К СВОЕМУ ХОЗЯИНУ.'

**Comment by grannypron** [comment]
Must not forget that I will probably need to adjust the byte-location-specific fixes for 36 and 45 after making this fix
