### ISSUE TITLE
Reassign View Character Screen Hotkeys

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#17]
The screen that comes up with the View command has *) menu items.  Find the correct offsets to change the hotkeys.

**Comment by grannypron** [comment]
Items, Spells, Trade, Drop, etc.   - 21AA7-21ACB
Should be Dto   Prfk   J<v   El. Yfp. Uth: 
<I - I is at 21CE2 - should be D
<S - S is at 21CF1 - should be P
<T - T is at 21D0E - should be J
<D - D is at 21D18 - should be E

**Comment by grannypron** [comment]
Still, even with these changes, Y is not causing the menu to exit.

**Comment by grannypron** [comment]
The two runs diverge here:

For the E press on the unmodified game:
0C9A:00000DDB  test es:[bx+di],al              es:[0A54]=0020         EAX:00000020 EBX:00000008 ECX:00000005 EDX:000003C5 ESI:00003BC5 EDI:00000A4C EBP:00003EAA ESP:00003D6E DS:0E1E ES:28E9 FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

Vs the Y press on the modified:
0C9A:00000DDB  test es:[bx+di],al              es:[0A57]=0000         EAX:00000002 EBX:0000000B ECX:00000001 EDX:000003C5 ESI:00003BC5 EDI:00000A4C EBP:00003EAA ESP:00003D6E DS:0E1E ES:28E9 FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

These return a different Z flag which causes the jne at 
28E9:00000AF1  je   00000AF6 ($+3)             
to jump vs not jump

**Comment by grannypron** [comment]
This looks a lot like the work done for the hotkeys for the combat main menu (attached)
[hotkeys_research.txt](https://github.com/grannypron/PoR_L10n/files/6373713/hotkeys_research.txt)


These relevant offsets in the GAME.OVR were found to be at 2D989 and 2D98B

**Comment by grannypron** [comment]
In memory at  28E90 + A54 = 298E4.  This is right above the menu item text.  So, we want to set the bytes such that es:[0A57] anded with 02 is not 0.  The relevant bytes for 0A57 are 21A91 & 21A92 in GAME.OVR - remember little endianness, We could just make 21A91 be FF, but to keep it minimal, we will change it to 02.  That does, indeed end up escaping the menu on a Y keypress.

The underlying logic for why/how these bytes are used is still somewhat of a mystery to me.  It may be that these byes that accompany the menu item strings somehow signify which keypresses will be "allowed" to exit the menu if the key falls through all the existing menu cmp operations (maybe a switch statement), but I don't know.  In any case, this pattern has been seen before.

**Comment by grannypron** [comment]
Then we also have to set 21A8E to 0 so that E is NOT used as an exit key for the menu.

**Comment by Reotor** [comment]
Since the allowable string length has become larger due to the change in hotkeys, the following adjustments must be made here:

[370](https://www.old-games.ru/translate/index.php?translationid=152&page=all#phrase370) | Items ---> Вещи ---> Dtob
[371](https://www.old-games.ru/translate/index.php?translationid=152&page=all#phrase371) | Spells ---> Закл. (dot at the end) ---> Pfrk.
[372](https://www.old-games.ru/translate/index.php?translationid=152&page=all#phrase372) | Trade ---> Обмен ---> J,vty
