### ISSUE TITLE
Reassign hotkeys for Place Exit menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#22]
This relates to the Place menu "Place Exit" text at D64E-D657 in the UNCOMPRESSED START.EXE which becomes Класть Уйти

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/116319505-3ca28800-a77c-11eb-8d08-33ec742e2580.png)

**Comment by Reotor** [comment]
> Класть (Place)

In my opinion, this word must be translated differently here. Can you explain in more detail what this option does in the game?

**Comment by Reotor** [comment]
> This relates to the Place menu "Place Exit" text at D64E-D657 in the UNCOMPRESSED START.EXE which becomes Класть Уйти

> Класть (Place)

In my opinion, this word must be translated differently here. Can you explain in more detail what this option does in the game?
