### ISSUE TITLE
Reassign hotkeys for Money Items menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#26]
This relates to the Money Items menu "Money Items Exit" at 62A6-62B5 in GAME.OVR which becomes Ден Вещ Уйти

**Comment by Reotor** [comment]
Money Items Exit ---> Деньг Вещи Уйти

**Comment by Reotor** [comment]
> This relates to the Money Items menu "Money Items Exit" at 62A6-62B5 in GAME.OVR which becomes Ден Вещ Уйти

Money Items Exit ---> Деньг Вещи Уйти
