### ISSUE TITLE
Reassign hotkeys for View Pool menu 

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#27]
This relates to the View Pool menu "View Pool Exit" at 63AD-63BA in GAME.OVR which becomes Г Пул Уйти

**Comment by Reotor** [comment]
View Pool Exit ---> Гер. Пул Уйти

**Comment by Reotor** [comment]
> This relates to the View Pool menu "View Pool Exit" at 63AD-63BA in GAME.OVR which becomes Г Пул Уйти

View Pool Exit ---> Гер. Пул Уйти
