### ISSUE TITLE
Two words merge into one, a space is required

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#3]
[390](https://www.old-games.ru/translate/index.php?translationid=152&page=all#phrase390) will be gone forever ---> пропадёт навсегда.

When trying to delete a character's item when a warning appears that the item will be deleted permanently, the "пропадёт" and previous word "дротиков" merge into one:

![space](https://user-images.githubusercontent.com/77742895/114731791-aff2d580-9d4a-11eb-90a1-dba6f51d93f3.jpg)

I tried to fix the problem by putting a space before "пропадёт" word in our translation system, but it didn't work...

**Comment by grannypron** [comment]
Now fixed in the latest patch
