### ISSUE TITLE
Reassign hotkeys for Detect Exit menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#30]
This relates to the Detect menu "Detect Exit" text at 63C3-63CD in GAME.OVR which becomes Опр. Уйти

**Comment by Reotor** [comment]
Detect Exit ---> Опред. Уйти

**Comment by Reotor** [comment]
> This relates to the Detect menu "Detect Exit" text at 63C3-63CD in GAME.OVR which becomes Опр. Уйти

Detect Exit ---> Опред. Уйти
