### ISSUE TITLE
Reassign hotkeys for Loot (with pooled money) menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#31]
This relates to the menu following combat for loot "View Take Pool Share" text at 63CF-63E2 in GAME.OVR which becomes Ге Вз Пул Ра

**Comment by Reotor** [comment]
View Take Pool Share ---> Гер. Вз. Пул **Д**ел.

**Comment by Reotor** [comment]
> **Д**ел.

or "Разд." However, the first variant, in my opinion, would be better...

**Comment by Reotor** [comment]
> This relates to the menu following combat for loot "View Take Pool Share" text at 63CF-63E2 in GAME.OVR which becomes Ге Вз Пул Ра

View Take Pool Share ---> Гер. Вз. Пул **Д**ел. (or "**Р**азд." However, the first variant, in my opinion, would be better...)
