### ISSUE TITLE
Reassign hotkeys for Loot menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#32]
This relates to the menu following combat for loot "View Take Pool" text at 63E4-63F1 in GAME.OVR which becomes Ге Вз Пул

**Comment by Reotor** [comment]
View Take Pool ---> Гер. Вз. Пул

**Comment by Reotor** [comment]
> This relates to the menu following combat for loot "View Take Pool" text at 63E4-63F1 in GAME.OVR which becomes Ге Вз Пул

View Take Pool ---> Гер. Вз. Пул
