### ISSUE TITLE
Reassign hotkeys for character icon selection menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#34]
This relates to the menu "Parts color-1 color-2 Size Exit" text at D889-D8A7 in the UNCOMPRESSED START.EXE which becomes Части цвет-1 цвет-2 Рост Уйти

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/116335204-1096ff00-a79c-11eb-821a-be3d71c93cef.png)

**Comment by Reotor** [comment]
> This relates to the menu "Parts color-1 color-2 Size Exit" text at D889-D8A7 in the UNCOMPRESSED START.EXE which becomes Части цвет-1 цвет-2 Рост Уйти

I think it would be more correct to change the "**Рост**" word to "**Размер**"
