### ISSUE TITLE
Reassign hotkeys for character Keep confirmation menu

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#35]
This relates to the menu "Keep Exit" text at D905-D90D in the UNCOMPRESSED START.EXE which becomes Оставить Уйти

**Comment by Reotor** [comment]
Will the "Оставить" word fit here?

**Comment by grannypron** [comment]
Yep it probably will because this string is in START.EXE and not GAME.OVR, and we found a lot more string space when we decompressed START.EXE
