### ISSUE TITLE
Change menu item for Place Exit menu

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#45]
> This relates to the Place menu "Place Exit" text at D64E-D657 in the UNCOMPRESSED START.EXE which becomes Класть Уйти

![116319505-3ca28800-a77c-11eb-8d08-33ec742e2580](https://user-images.githubusercontent.com/77742895/116761824-5284a700-aa21-11eb-9d0a-34a8ac4680bb.png)

> Класть (Place)

In my opinion, this word must be translated differently here. Can you explain in more detail what this option does in the game?

_Originally posted by @Reotor in https://github.com/grannypron/PoR_L10n/issues/22#issuecomment-830445384_

**Comment by grannypron** [comment]
This is for when you use the Alter -> Order menu.  Once you Select a character.

**Comment by Reotor** [comment]
> This is for when you use the Alter -> Order menu. Once you Select a character.

Then it needs to be translated as "**С**тавить" (not as "Класть")
