### ISSUE TITLE
Reassign hotkeys for character Cast menu item

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#46]
This relates to the menu "Cast" text at 27019-2701C in GAME.OVR which becomes Закл

**Comment by grannypron** [comment]
I think I accidentally fixed this one with #57?

**Comment by Reotor** [comment]
> I think I accidentally fixed this one with #57?

I will definitely review all your corrections as soon as free time becomes available. May is a very busy month at my work. In June, July, August, I will have much more free time and I will be able to tackle the project closely. At the moment, I try to devote a little time to the project every day, but this is far from always possible. 

**Thank you very much for your work! What you have done while working on the translation is worthy of great respect!**
