### ISSUE TITLE
"Yes No" string is not translated in GAME.OVR

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#5]
See #4:

"..there is one location where the "Yes No" string is stored in GAME.OVR, but it does not use the ~ for specifying hotkeys. Until/unless we find a way of changing the hotkeys for that string, changing the "Yes No" to "да нет", will result in the user not being able to select either. Since the string is in GAME.OVR, there is no uncompressing we can do to make the string longer, either."

This task is to either change the string to use the prefixes or figure out the hotkeys.

**Comment by grannypron** [comment]
I think I mananged to trace down and modify the necessary instructions to switch the hotkeys for this string.   Latest patch should now have the Yes/No for the Drop It changed and working with L/Y hotkeys.  Hopefully this will change it in other places as well.  Updated notes are attached (lines 446+ are relevant) to this particular ticket.
[hotkeys_research.txt](https://github.com/grannypron/PoR_L10n/files/6328019/hotkeys_research.txt)

**Comment by Reotor** [comment]
> Latest patch should now have the Yes/No for the Drop It changed and working with L/Y hotkeys. Hopefully this will change it in other places as well. 

Yes, this works in "drop item" dialog (and hotkeys too), but doesn't seem to work anywhere else. 

![fix5](https://user-images.githubusercontent.com/77742895/115089092-3c9fbe00-9f1a-11eb-8618-229c2cc7185d.jpg)

I checked this at the temple and with the merchant (and doesn't work).

![здгкфд1](https://user-images.githubusercontent.com/77742895/115089434-e2ebc380-9f1a-11eb-8409-c78684e8ea95.jpg)
