### ISSUE TITLE
Reassign hotkeys for Bash menu item

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#50]
This relates to the menu "Bash" text at 17418-1741B in GAME.OVR which becomes Бить 

Hotkey is probably at offset 17591

**Comment by grannypron** [comment]
I had to use the second character because Б maps to < which the game doesn't seem to allow as a hotkey.  Still should work though.

**Comment by Reotor** [comment]
> I had to use the second character because Б maps to < which the game doesn't seem to allow as a hotkey. Still should work though.

We can use "Удар" word here, which mean about the same.

**Comment by grannypron** [comment]
> > I had to use the second character because Б maps to < which the game doesn't seem to allow as a hotkey. Still should work though.
> 
> We can use "Удар" word here, which mean about the same.

That would confllct with Уйти

**Comment by Reotor** [comment]
> That would confllct with Уйти

Well... Can we use "Наз." instead "Уйти" here? (As you did before in some other menus).

**Comment by grannypron** [comment]
Possibly.  I've noticed that there might be some side-effects to changing the Exit hotkey.  It seems like it might be tied to clearing the screen or something.  I'll leave this open for now and investigate after we do the easier ones if it's still worth it.  Using the capital и seems to be working for the moment.

**Comment by Reotor** [comment]
Of course, as a last resort, do as you originally planned (hotkey for the second character for the "Бить" word).
