### ISSUE TITLE
Reassign hotkeys for Delay Quit menu items

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#53]
This relates to the menu "Delay Quit" text at A60D-A616 in GAME.OVR which becomes Позже Уйти

**Comment by grannypron** [comment]
@Reotor
Can I use Наз. for Quit?  Delay Quit is paired with Speed Exit in the Done combat submenu and so using Уйти duplicates it.

In this menu, Quit ends the turn, and Exit just leaves the menu.

![image](https://user-images.githubusercontent.com/19980049/116834706-e8851280-ab84-11eb-99d9-30bb797f8466.png)

**Comment by Reotor** [comment]
> Can I use Наз. for Quit?

No, this translation is not suitable here. Let's do it like this:

Exit ---> Уйти ---> Eqnb
Quit ---> Всё ---> Dc`
