### ISSUE TITLE
Change Buy menu hotkeys

### ISSUE THREAD

**Issue by grannypron** [grannypron/PoR_L10n#61]
"Buy View Take Pool Share Appraise Exit" should be changed from 

Куп Гер Вз Пул Раз Оце Уйти
to 
Куп Гер Вз Пул Дел Оценить Уйт

So the Р hotkey will be changed Р -> Д as well as the menu text

**Comment by Reotor** [comment]
> Куп Гер Вз Пул Дел Оценить Уйт

*Куп Гер Вз Пул Дел Оценить Уйт**и**
