### ISSUE TITLE
After installing the last patch, the game does not start

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#69]
I installed the latest patch (where "Added Google Translate of ECL3, segment 0"). I installed the latest patch, but the game stopped starting after that. Without installing the patch, the game starts normally.

**Comment by grannypron** [comment]
This is probably because the patch zip got double-nested sorry.  I updated it.  Be sure that the POOLRAD/patch directory has files in it instead of a subfolder inside the subfolder (i.e. POOLRAD/patch/patch)

Lmk if it does not work.

**Comment by Reotor** [comment]
> This is probably because the patch zip got double-nested sorry. I updated it. Be sure that the POOLRAD/patch directory has files in it instead of a subfolder inside the subfolder

No, the problem is something else. The directory structure is fine.

![Screenshot_10](https://user-images.githubusercontent.com/77742895/120525137-794b4a00-c3e0-11eb-934d-e65ff2ecc600.jpg)

**Comment by Reotor** [comment]
Perhaps I understand what the problem is. After installing the patch, the new 8X8D1.DAX, ECL3.DAX, GAME.OVR, TITLE.DAX was created and old ones received the ".old" extensions.

![Screenshot_11](https://user-images.githubusercontent.com/77742895/120527306-dba54a00-c3e2-11eb-9a06-296ded7e9ce8.jpg)

But no new "START.EXE" file was created.

**Comment by Reotor** [comment]
I was able to start the game by renaming the "START.EXE.old" to "START.EXE" file, but since it is old, the text in this file is not translated and hotkeys not work.

![Screenshot_12](https://user-images.githubusercontent.com/77742895/120528875-95e98100-c3e4-11eb-8e99-37bcb152ddb6.jpg)

**Comment by grannypron** [comment]
Yeah no the start.exe.old is just the unpatched version.  I tried it on a new install and it started ok for me.  Can you look in the command prompt window that you run when you do the patch and see if there are any error messages?

**Comment by grannypron** [comment]
I think you will see this:  

oldFile dataSize 65231 != diffFile saved oldDataSize 70864 ERROR!

That's probably the problem.  I just created the diff against a bad copy of start.exe.  Lmk if you are seeing something else.

**Comment by Reotor** [comment]
I did it all over again, the problem remained relevant. File START.EXE is missing. Here are screenshots of command prompt window:

![Screenshot_6](https://user-images.githubusercontent.com/77742895/120654815-b5d38000-c48a-11eb-98fc-3bcb5a11880d.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/77742895/120654833-b8ce7080-c48a-11eb-8b56-05ac0c539d8c.jpg)

**Comment by Reotor** [comment]
And by the way, yes! The first screenshot shows an error message regarding START.EXE file, exactly as you said.

**Comment by grannypron** [comment]
Alright I think I got it now.

**Comment by grannypron** [comment]
One more thing - be sure to leave and/or re-enter the civilized area so that the ECL gets reloaded to see the changes.  It stores a copy of the ECL along with the save file.

**Comment by Reotor** [comment]
> One more thing - be sure to leave and/or re-enter the civilized area so that the ECL gets reloaded to see the changes. It stores a copy of the ECL along with the save file.

It's okay now, thanks! I suppose you will now be waiting for us to finish translating the ECL files? Or maybe it is worth transferring the translation into the game in parts, by areas? This way we could quickly correct various shortcomings in the translation...

**Comment by grannypron** [comment]
Not waiting  - I still have some things to figure out with the ECLs.  I hit you up in the gitter about it.  I'd say yes, do one ECL at a time.  That way I can work out the technical hurdles with them and the translators can move on to the next.
