### ISSUE TITLE
Need to change main menu item and hotkey

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#71]
![Screenshot_10](https://user-images.githubusercontent.com/77742895/120717386-1d5fee80-c4d0-11eb-8c87-4795b222ef1b.jpg)

To get rid of the parenthesis, I suggest making the following change here:

**У**)лагерь ---> **П**ривал
**E**)kfuthm ---> **G**hbdfk

This word means the same thing, but this way we get rid of the repetition of the hotkey.

**Comment by Reotor** [comment]
Although, I do not see what the hotkey may intersect with "Л" here. If I'm right, please remove "У)" here and change the hotkey to "Л" (K). Let it be just ЛАГЕРЬ ---> KFUTHM.

If there really is some kind of hotkey intersection, let it be ПРИВАЛ ---> GHBDFK (hotkey "П").

**Comment by grannypron** [comment]
No there was no hotkey duplication, it was just that I couldn't figure out how to change that hot key.  It might be doing some kind of "fall through" in the case or something idk.  I need to look at it again.

**Comment by grannypron** [comment]
Initial look at the divergence might show that we need to add this swap: **4115|4B

**Comment by grannypron** [comment]
Still didn't work after changing that one.  Running another parallel trace showed another divergence.  After changing that one, it worked.
