### ISSUE TITLE
Ingame "Exit to DOS" option. Russian hotkeys not working korrect

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#72]
When the group in camp and I try to exit to DOS after save a game, the options "Да"/"Нет" don't working korrect. Apparently, the English keyboard shortcut for "Yes" option still works. And the old "N" hotkey do nothing here. 

![EXIT_DOS](https://user-images.githubusercontent.com/77742895/124613815-4e8b6000-de7c-11eb-99c8-1744ca08b18a.jpg)

I suppose it is necessary to change the hotkeys here to "Д" (L) for "Да" and "Н" (Y) for "Нет" option.

**Comment by grannypron** [comment]
Fix is to chage 197A0 in GAME.OVR from 59 to 4C
