### ISSUE TITLE
Needs symmetry adjustments on the character creation screen

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#73]
Need to make a couple of lines on the character characteristics screen more symmetrical with respect to other lines (as original).

For more details see the picture:

![simmetric_correction](https://user-images.githubusercontent.com/77742895/124616066-754a9600-de7e-11eb-82fc-75c41b5518bc.jpg)

If it is difficult to carry out, then it is not necessary ...

**Comment by grannypron** [comment]
This is probably fixed around the area of 215F0 in GAME.OVR and probably has something to do with whitespace padding and string length

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/133351965-b1f25d77-7416-40ae-acb5-c19c9b463a73.png)

Ah so what is going on here is that the THAC0, Damage, Encumberance, and Movement strings are all supposed to be RIGHT aligned.  With the strings shortened, they need more left space padding.
