### ISSUE TITLE
Character icon colors does not change when customizing

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#75]
When customizing the character icon, when we go to the path: "color-1" (цвет-1) or "color-2" (цвет-2) ---> "weapon" (оружие), "body" (тело), etc the options "next" (след.) and "prev" (пред.) do nothing with the icon colors. "Keep" (остав.) option, also do nothing here. Although I can see the options respond to hotkeys.

![weapon_colors](https://user-images.githubusercontent.com/77742895/124677992-4c4ff280-deca-11eb-852c-ca3fa7ef7a97.jpg)

Although in the original game the colors change correctly.

I have a suspicion that these settings do not work due to the fact that the hotkeys in the "ЦВЕТ-**1**" (color-1) and "ЦВЕТ-**2**" (color-2) options do not work correctly.

**Comment by grannypron** [comment]
Just forgot the hotkeys on this one.  Should be in there now.
