### ISSUE TITLE
Wherever in translation, we wanted to put a single quote ('), the letter "Э" is displayed

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#78]
Wherever in translation, we wanted to put a single quote ('), the letter "Э" is displayed. 

![`](https://user-images.githubusercontent.com/77742895/124682283-119e8800-ded3-11eb-855c-1f16249b5e46.jpg)

**Comment by grannypron** [comment]
Should be good with the fix for #80
