### ISSUE TITLE
"PRESS <ENTER>/<RETURN> TO CONTINUE" not translated

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#79]
Message "PRESS <ENTER>/<RETURN> TO CONTINUE" not translated in game dialogs. See the picture:

![ENTER](https://user-images.githubusercontent.com/77742895/124682936-ad7cc380-ded4-11eb-8fb4-93fec7c0a2e2.jpg)

It is necessary to translate this as "**НАЖМИТЕ ВВОД, ЧТОБЫ ПРОДОЛЖИТЬ**"

**Comment by grannypron** [comment]
This is probably the one at 1DCC-1DEF in game.ovr.  Or 1DF1-1E12.  This is probably my mistake by changing 37 & 38 in game.ovr.translations to not have the < and > characters.
