### ISSUE TITLE
"EXIT" option not translated

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#8]
At the stage of character creation, I found out that the "EXIT" option was not translated (although it was translated in our translation system).  We need to translate it: "**E**XIT" ---> "**У**ЙТИ". Hotkeys will match.

![exit](https://user-images.githubusercontent.com/77742895/115094059-e84e0b80-9f24-11eb-9f0a-f8379364877c.jpg)

I also remember that this option was not translated in some other places, but I don’t remember exactly where ...

**Comment by grannypron** [comment]
Found it at 2D665-2D668 in GAME.OVR.  Also caught a couple of extra "Exit" strings and changed them.  Latest patch contains fix.
