### ISSUE TITLE
The letter "Ё" is missing everywhere in game

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#80]
The letter "Ё" is missing everywhere in game. 

![JIVET](https://user-images.githubusercontent.com/77742895/124683723-65f73700-ded6-11eb-9e66-641e555e67a1.jpg)

I remember once you wrote something in our forum about - how to put this letter in our case. But I don't remember how. 

Please remind me how to do this. And if possible to do fast, insert this letter into our translation, where it is present. Because doing it manually takes a very long time.

**Comment by Reotor** [comment]
*If this letter is not available to us for use, we can replace it everywhere with "E".

**Comment by Reotor** [comment]
I found [your message on our forum](https://www.old-games.ru/forum/threads/pool-of-radiance.97690/page-4#post-1715305) with keyboard layout. Apparently, we should have used a "@" symbol, but we didn't. I hope it will be possible to somehow automate this replacement, because we have too many strings with "Ё" letter to correct it manually.

**Comment by grannypron** [comment]
You guys are doing the right thing.  No need to substitute Ё in your translation system.  I don't know why it's not ending up in the game right now, but I will check it out

**Comment by grannypron** [comment]
Aahahahaaaaaa I think I see it.   Effectively the " and the @ are being switched in my routine.  This probably has something to do with the way that " used to be above the 2 on old keyboards and now it is above the ' in the place that " is on new keyboards.  That is, @ and " switched places on newer keyboards!

**Comment by grannypron** [comment]
Well, @ wasn't being printed for whatever reason.  Even though it does print that character when the user types "@" on input.  No big deal, I found out that we can use _ and which place corresponds to it on the font map.

**Comment by Reotor** [comment]
Since the [last patch](https://github.com/grannypron/PoR_L10n/blob/main/downloads/patch.zip) returned the letter "Ё" and quotes problem (In fact, this is just the previous patch), I reopen this issue
