### ISSUE TITLE
"Press any key to continue" not translated

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#82]
"Press any key to continue" not translated.

![press any key to](https://user-images.githubusercontent.com/77742895/124686967-b6719300-dedc-11eb-8514-1b7d35677e4c.jpg)

Need to translate it as "**НАЖМИТЕ ЛЮБУЮ КЛАВИШУ**"

**Comment by grannypron** [comment]
This is now fixed.  Probably with #89
