### ISSUE TITLE
YES/NO options from ingame temple dialogs not translated

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#83]
YES/NO options from ingame temple dialogs not translated:

![YES-NO](https://user-images.githubusercontent.com/77742895/124688659-d5bdef80-dedf-11eb-9f92-ae91dbd1eb6a.jpg)

YES - **Д**А
NO - **Н**ЕТ

Also need to make the appropriate hotkeys. ("Д" for "ДА" and "Н" for "НЕТ").

**Comment by Reotor** [comment]
I have just translated all these "YES/NO" strings in all ECL files in our [translation system](https://www.old-games.ru/translate/). So the problem will be solved in any case with the future transfer of the translated strings to the game.

**Comment by grannypron** [comment]
This is fixed with the #140  - b5977b2
