### ISSUE TITLE
The game freezes in traning hall

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#88]
The game freezes after a positive response to arena master's offer to join the team for NPC.

![soratnik_errorENG](https://user-images.githubusercontent.com/77742895/125018584-13f11580-e07e-11eb-8d57-8ad6f9738e10.jpg)
![soratnik_error](https://user-images.githubusercontent.com/77742895/125018954-b7dac100-e07e-11eb-9b3b-109efecd0948.jpg)

**Comment by grannypron** [comment]
This was fixed with #89 fix
