### ISSUE TITLE
It is necessary to somehow implement translated names of monsters directly into the patch

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#94]
It is necessary to somehow implement names of monsters (MON1CHA.DAX - MON8CHA.DAX), translated using GBC, directly into the patch. It will not be very user-friendly to install these components separately.

_*If necessary, I can provide archives with translated **.DAX** and **.hdiff** files..._

**Comment by grannypron** [comment]
Sure - just attach the hdiffs and I will include the along with commands to patch them in the patch.bat.

**Comment by Reotor** [comment]
[hdiff.zip](https://github.com/grannypron/PoR_L10n/files/6822313/hdiff.zip)

**Comment by grannypron** [comment]
Alright - should be in there!

**Comment by Reotor** [comment]
> Alright - should be in there!

TY! I will check it later, when there are more closed issues.
