### ISSUE TITLE
YES/NO options from ingame dialogs not translated

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#95]
YES/NO options from ingame inn, shops, temple, etc dialogs not translated:

![inn](https://user-images.githubusercontent.com/77742895/125995538-e533e7f4-a879-454e-9c66-55fed7131f49.jpg)

YES - ДА
NO - НЕТ

Also need to make the appropriate hotkeys. ("Д" for "ДА" and "Н" for "НЕТ").

**Comment by grannypron** [comment]
Now fixed with the fix for #140 - b5977b2
