### ISSUE TITLE
Need a translation correction in the shop menu

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#96]
Need a translation correction in the shop menu:

![lavka1](https://user-images.githubusercontent.com/77742895/125997315-132cbd93-9e8b-4168-aa82-4f15080dca3f.jpg)

![lavka](https://user-images.githubusercontent.com/77742895/125996907-f1e326da-6719-49a6-b11b-76dddb03c6f0.jpg)

"лавк" ---> "лавка" (very desirable, if possible)
"сл" ---> "след"
"пр" ---> "пред"
"наз." ---> "наз" (remove the dot at the end)

**Comment by grannypron** [comment]
We only have 4 characters available for "Shop", sorry :/ 

I made the other changes.
