### ISSUE TITLE
Hotkey not changed for "TRADE" dialog

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#98]
When we go: "VIEW" (ГЕР) ---> "TRADE" (ОБМЕН)---> "SELECT" (ВЫБОР) at the main party menu, the "SELECT" (ВЫБОР) option activate by "Ы" (S) hotkey.

![ЫУДУСЕ](https://user-images.githubusercontent.com/77742895/126000441-c5a721b6-bcce-4109-a089-6a2c07025cc9.jpg)

We need to change "Ы" (S) to "В" (D) hotkey.

_*Perhaps you deliberately left this hotkey unchanged here so that it does not overlap with other keys in other menus. **But if possible, it is highly advisable to fix this hotkey**._

**Comment by grannypron** [comment]
Aha!  This is where the Select from #60 is used.

**Comment by grannypron** [comment]
Now, this looks like the comparison string in question:

025C:00002DD6  cmp  byte [bp-2A],45            ss:[3B04]=0953         EAX:00000008 EBX:0000000A ECX:00000003 EDX:00003E18 ESI:00003721 EDI:00003D6E EBP:00003B2E ESP:000038D4 DS:0E1E ES:1694 FS:0000 GS:0000 SS:1694 CF:0 ZF:1 SF:0 OF:0 AF:0 PF:1 IF:1

But, that would imply that the game checks for "E" and (probably) exits the screen but then whatever the other key is, it selects that user.  But changing the capital doesn't seem to be enough here so something else is going on.

**Comment by grannypron** [comment]
Diverges here:

For the S press:
0C9A:00000DDB  test es:[bx+di],al              es:[2C29]=0008         EAX:00000008 EBX:0000000A ECX:00000003 EDX:00003E18 ESI:00003721 EDI:00002C1F EBP:00003B2E ESP:000038CA DS:0E1E ES:025C FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

For the D press:
0C9A:00000DDB  test es:[bx+di],al              es:[2C27]=0020         EAX:00000010 EBX:00000008 ECX:00000004 EDX:00003E18 ESI:00003721 EDI:00002C1F EBP:00003B2E ESP:000038CA DS:0E1E ES:025C FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

**Comment by grannypron** [comment]
Note the translation for "Trade" has changed in the scope of #102

**Comment by grannypron** [comment]
es:[2C27] maps to the 20 in this block of the stack at 51E7

0000:5187     50 B0 00 50 8D 7E FF 16 57 BF 87 2B 0E 57 9A 0B  P..P.~..W..+.W.. 
0000:5197     0B 9A 0C 9A E8 02 93 05 B0 00 50 B0 17 50 B0 27  ..........P..P.' 
0000:51A7     50 B0 18 50 9A 37 01 93 05 C4 3E 16 67 26 8A 45  P..P.7....>.g&.E 
0000:51B7     02 98 05 03 00 50 C4 3E 16 67 26 8A 45 03 98 05  .....P.>.g&.E... 
0000:51C7     03 00 50 B0 FF 50 B0 08 50 9A 52 00 82 05 89 EC  ..P..P..P.R..... 
0000:51D7     5D CB 05 20 45 71 6E 62 00 20 00 08 00 00 00 00  ].. Eqnb. ...... 
0000:51E7     20 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00   ............... 
0000:51F7     00 00 00 00 00 00 00 00 01 20 06 44 73 3C 6A 68  ......... .Ds<jh 

But where does that come from I wonder?

**Comment by grannypron** [comment]
Probably this block in 4080 of START.EXE (uncompressed):

67 26 8A 45 03 98 05 03 00 50 B0 FF 50 B0 08 50                       g&ŠE˜�P°ÿP°P
9A 52 00 E0 03 89 EC 5D CB 05 20 45 78 69 74 00                      šR�à‰ì]Ë Exit� 
20 00 08 00 00 00 00 20 00 08 00 00 00 00 00 00                      ����� ��������
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01                      ��������������
20 06 53 65 6C 65 63 74 55 89 E5 81 EC 5A 02 C4                      SelectU‰åìZÄ
 7E 0C 06 57 8D 7E D7 16 57 B8 28 00 50 9A 25 0B                    ~W~×W¸(�Pš%

**Comment by grannypron** [comment]
I think if I change that 20 at 0x40A7 to 10 then the test call will return 0 and it will work.

**Comment by grannypron** [comment]
It does, in fact cause the hotkey to change, but then the game freezes after selecting a person.

**Comment by grannypron** [comment]
But, this seems to be happening even when the Select hotkey stays S.  We may have a separate bug to file/fix here.

**Comment by grannypron** [comment]
It does seem to work, but then the E key does not work to exit the select menu

**Comment by grannypron** [comment]
Actually the E in this case has an interesting effect where it selects 0 players and if you then hit enter it escapes back.

**Comment by grannypron** [comment]
In regards to the E keypress, the divergence occurs here:
In the original:
0C9A:00000DDB  test es:[bx+di],al              es:[0A9D]=0018         EAX:00000010 EBX:0000000A ECX:00000004 EDX:00000000 ESI:00003721 EDI:00000A93 EBP:00003EAA ESP:00003D6E DS:0E1E ES:28E9 FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

vs in the now modded version:

0C9A:00000DDB  test es:[bx+di],al              es:[0A9B]=0200         EAX:00000008 EBX:00000008 ECX:00000003 EDX:00000000 ESI:00003721 EDI:00000A93 EBP:00003EAA ESP:00003D6E DS:0E1E ES:28E9 FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

Looking at 2992D in memory (28E90 + 09AD) shows 0218, which is only (fortunately), only found in a few places in GAME.OVR and the relevant location is clearly at 21AD6

**Comment by grannypron** [comment]
OK so now after the change when E is pressed, there remains a divergence here because EAX is 20 which now does not return a non-zero with 10

0C9A:00000DDB  test es:[bx+di],al              es:[2C27]=0010         EAX:00000020 EBX:00000008 ECX:00000005 EDX:00000000 ESI:00003721 EDI:00002C1F EBP:00003B2E ESP:000038CA DS:0E1E ES:025C FS:0000 GS:0000 SS:1694 CF:0 ZF:0 SF:0 OF:0 AF:1 PF:0 IF:1

So now I need to not use 10 but to use a number that has a nonzero result when and'ed with both 20 and 10.

**Comment by grannypron** [comment]
30 works nicely
