### ISSUE TITLE
"HP" abbreviation not translated at character's window

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#99]
"HP" abbreviation not translated at character window:

![РЗ](https://user-images.githubusercontent.com/77742895/126001822-50435bcb-c0fc-4841-815e-577ac2660664.jpg)

Need to translate it as "ОЗ" (JP).

**Comment by grannypron** [comment]
I changed HP to JP in every place that I could find in the START.EXE and it doesn't seem to update that string in the view screen.  Not sure where that string is coming from yet.
